### ISSUE TITLE
Tab hiding API has landed!

### ISSUE THREAD

**Issue by irvinm** [photodiode/panorama-view#4]
https://bugzilla.mozilla.org/show_bug.cgi?id=1423725

It is currently in FF59a1+ and behind a configuration setting, but certainly something to work with!

**Comment by WladyX** [comment]
I am on FF 59.0b7 and have set the extensions.webextensions.tabhide.enabled to enabled, but the tabs do not hide, how can I enable it?
Thanks!

**Comment by Preman-Kampung** [comment]
I'm on Nightly build and the tab hiding didn't work. When using connex addon, the tab hiding is working just fine.

**Comment by photodiode** [comment]
Sorry about this, there was a stupid mistake in the code.
I think it should work with v0.6.17

**Comment by WladyX** [comment]
Thanks for the fast update, however this still does not work for me after updating to 0.6.17 :)

**Comment by Preman-Kampung** [comment]
Not working for me either.

**Comment by photodiode** [comment]
New update up (v0.6.18). Really hope it's fixed now.
I'm working a bit blind right now as I don't have v59 here, hehe.

**Comment by WladyX** [comment]
Nope, still not, also the pinned tabs are showing in their own group, maybe a bug?
You are testing directly on us? :))

**Comment by photodiode** [comment]
Sorry, but yes. Haha
This is weird.. not sure what could be.... OOOOOH
I forgot to add the permission!

**Comment by WladyX** [comment]
Works now, thanks!!

**Comment by PrototypeNM1** [comment]
We can mark this as closed, issue fixed in https://github.com/photodiode/panorama-view/commit/6acf99788f82c4e2953901d5f1dbbbcf6133fb78
